auto: true
server: true
baseurl: /remembering-catastrophe
permalink: /:categories/:title/
exclude: [newpics, data]
prose:
  rooturl: "_posts"
countries:
  - Austria
  - Belarus
  - Czech Republic
  - France
  - Germany
  - Latvia
  - Lithuania
  - Poland
  - The Netherlands
  - Ukraine
  - United Kingdom